wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711286387.0
    t:
      1:
      - 1
      - 35
      - 41
      - 55
      2:
      - 1
      - 35
      - 41
      - 55
      3:
      - 23
      4: 3.11.7
      5: 0.16.4
      8:
      - 3
      - 5
      13: windows-amd64
n_layers:
  desc: null
  value: 12
lr:
  desc: null
  value: 0.0031367085665902367
optimizer:
  desc: null
  value: SGD
features_lineales:
  desc: null
  value: 200
kernel_size_0:
  desc: null
  value: 27
padding_0:
  desc: null
  value: 19
bias_0:
  desc: null
  value: true
channels_0:
  desc: null
  value: 170
strides0:
  desc: null
  value: 100
pool_kernel0:
  desc: null
  value: 6
stride_kernel0:
  desc: null
  value: 5
kernel_size_1:
  desc: null
  value: 40
padding_1:
  desc: null
  value: 15
bias_1:
  desc: null
  value: true
channels_1:
  desc: null
  value: 68
strides1:
  desc: null
  value: 182
pool_kernel1:
  desc: null
  value: 8
stride_kernel1:
  desc: null
  value: 1
kernel_size_2:
  desc: null
  value: 36
padding_2:
  desc: null
  value: 4
bias_2:
  desc: null
  value: true
channels_2:
  desc: null
  value: 46
strides2:
  desc: null
  value: 134
pool_kernel2:
  desc: null
  value: 3
stride_kernel2:
  desc: null
  value: 10
kernel_size_3:
  desc: null
  value: 44
padding_3:
  desc: null
  value: 6
bias_3:
  desc: null
  value: false
channels_3:
  desc: null
  value: 24
strides3:
  desc: null
  value: 127
pool_kernel3:
  desc: null
  value: 6
stride_kernel3:
  desc: null
  value: 8
kernel_size_4:
  desc: null
  value: 9
padding_4:
  desc: null
  value: 20
bias_4:
  desc: null
  value: false
channels_4:
  desc: null
  value: 40
strides4:
  desc: null
  value: 248
pool_kernel4:
  desc: null
  value: 8
stride_kernel4:
  desc: null
  value: 4
kernel_size_5:
  desc: null
  value: 16
padding_5:
  desc: null
  value: 6
bias_5:
  desc: null
  value: true
channels_5:
  desc: null
  value: 129
strides5:
  desc: null
  value: 59
pool_kernel5:
  desc: null
  value: 8
stride_kernel5:
  desc: null
  value: 9
kernel_size_6:
  desc: null
  value: 41
padding_6:
  desc: null
  value: 17
bias_6:
  desc: null
  value: true
channels_6:
  desc: null
  value: 127
strides6:
  desc: null
  value: 23
pool_kernel6:
  desc: null
  value: 2
stride_kernel6:
  desc: null
  value: 5
kernel_size_7:
  desc: null
  value: 13
padding_7:
  desc: null
  value: 8
bias_7:
  desc: null
  value: false
channels_7:
  desc: null
  value: 254
strides7:
  desc: null
  value: 22
pool_kernel7:
  desc: null
  value: 8
stride_kernel7:
  desc: null
  value: 1
kernel_size_8:
  desc: null
  value: 1
padding_8:
  desc: null
  value: 8
bias_8:
  desc: null
  value: false
channels_8:
  desc: null
  value: 199
strides8:
  desc: null
  value: 199
pool_kernel8:
  desc: null
  value: 5
stride_kernel8:
  desc: null
  value: 2
kernel_size_9:
  desc: null
  value: 33
padding_9:
  desc: null
  value: 10
bias_9:
  desc: null
  value: true
channels_9:
  desc: null
  value: 137
strides9:
  desc: null
  value: 159
pool_kernel9:
  desc: null
  value: 4
stride_kernel9:
  desc: null
  value: 5
kernel_size_10:
  desc: null
  value: 2
padding_10:
  desc: null
  value: 14
bias_10:
  desc: null
  value: false
channels_10:
  desc: null
  value: 254
strides10:
  desc: null
  value: 241
pool_kernel10:
  desc: null
  value: 4
stride_kernel10:
  desc: null
  value: 1
kernel_size_11:
  desc: null
  value: 25
padding_11:
  desc: null
  value: 17
bias_11:
  desc: null
  value: false
channels_11:
  desc: null
  value: 66
strides11:
  desc: null
  value: 97
pool_kernel11:
  desc: null
  value: 5
stride_kernel11:
  desc: null
  value: 4
