wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711286287.0
    t:
      1:
      - 1
      - 35
      - 41
      - 55
      2:
      - 1
      - 35
      - 41
      - 55
      3:
      - 2
      - 23
      4: 3.11.7
      5: 0.16.4
      8:
      - 3
      - 5
      13: windows-amd64
n_layers:
  desc: null
  value: 30
lr:
  desc: null
  value: 0.0005731045242348907
optimizer:
  desc: null
  value: SGD
features_lineales:
  desc: null
  value: 131
kernel_size_0:
  desc: null
  value: 29
padding_0:
  desc: null
  value: 20
bias_0:
  desc: null
  value: true
channels_0:
  desc: null
  value: 51
strides0:
  desc: null
  value: 86
pool_kernel0:
  desc: null
  value: 2
stride_kernel0:
  desc: null
  value: 9
kernel_size_1:
  desc: null
  value: 17
padding_1:
  desc: null
  value: 11
bias_1:
  desc: null
  value: true
channels_1:
  desc: null
  value: 74
strides1:
  desc: null
  value: 176
pool_kernel1:
  desc: null
  value: 3
stride_kernel1:
  desc: null
  value: 8
kernel_size_2:
  desc: null
  value: 48
padding_2:
  desc: null
  value: 4
bias_2:
  desc: null
  value: false
channels_2:
  desc: null
  value: 8
strides2:
  desc: null
  value: 225
pool_kernel2:
  desc: null
  value: 8
stride_kernel2:
  desc: null
  value: 8
kernel_size_3:
  desc: null
  value: 14
padding_3:
  desc: null
  value: 14
bias_3:
  desc: null
  value: false
channels_3:
  desc: null
  value: 62
strides3:
  desc: null
  value: 132
pool_kernel3:
  desc: null
  value: 9
stride_kernel3:
  desc: null
  value: 6
kernel_size_4:
  desc: null
  value: 3
padding_4:
  desc: null
  value: 17
bias_4:
  desc: null
  value: true
channels_4:
  desc: null
  value: 96
strides4:
  desc: null
  value: 174
pool_kernel4:
  desc: null
  value: 7
stride_kernel4:
  desc: null
  value: 4
kernel_size_5:
  desc: null
  value: 50
padding_5:
  desc: null
  value: 8
bias_5:
  desc: null
  value: false
channels_5:
  desc: null
  value: 227
strides5:
  desc: null
  value: 99
pool_kernel5:
  desc: null
  value: 1
stride_kernel5:
  desc: null
  value: 9
kernel_size_6:
  desc: null
  value: 31
padding_6:
  desc: null
  value: 9
bias_6:
  desc: null
  value: false
channels_6:
  desc: null
  value: 39
strides6:
  desc: null
  value: 30
pool_kernel6:
  desc: null
  value: 10
stride_kernel6:
  desc: null
  value: 2
kernel_size_7:
  desc: null
  value: 50
padding_7:
  desc: null
  value: 16
bias_7:
  desc: null
  value: true
channels_7:
  desc: null
  value: 134
strides7:
  desc: null
  value: 47
pool_kernel7:
  desc: null
  value: 4
stride_kernel7:
  desc: null
  value: 5
kernel_size_8:
  desc: null
  value: 25
padding_8:
  desc: null
  value: 15
bias_8:
  desc: null
  value: false
channels_8:
  desc: null
  value: 212
strides8:
  desc: null
  value: 190
pool_kernel8:
  desc: null
  value: 8
stride_kernel8:
  desc: null
  value: 7
kernel_size_9:
  desc: null
  value: 40
padding_9:
  desc: null
  value: 4
bias_9:
  desc: null
  value: false
channels_9:
  desc: null
  value: 33
strides9:
  desc: null
  value: 93
pool_kernel9:
  desc: null
  value: 3
stride_kernel9:
  desc: null
  value: 2
kernel_size_10:
  desc: null
  value: 18
padding_10:
  desc: null
  value: 20
bias_10:
  desc: null
  value: false
channels_10:
  desc: null
  value: 112
strides10:
  desc: null
  value: 300
pool_kernel10:
  desc: null
  value: 1
stride_kernel10:
  desc: null
  value: 6
kernel_size_11:
  desc: null
  value: 49
padding_11:
  desc: null
  value: 13
bias_11:
  desc: null
  value: false
channels_11:
  desc: null
  value: 207
strides11:
  desc: null
  value: 80
pool_kernel11:
  desc: null
  value: 4
stride_kernel11:
  desc: null
  value: 3
kernel_size_12:
  desc: null
  value: 20
padding_12:
  desc: null
  value: 7
bias_12:
  desc: null
  value: false
channels_12:
  desc: null
  value: 53
strides12:
  desc: null
  value: 234
pool_kernel12:
  desc: null
  value: 9
stride_kernel12:
  desc: null
  value: 6
kernel_size_13:
  desc: null
  value: 27
padding_13:
  desc: null
  value: 2
bias_13:
  desc: null
  value: true
channels_13:
  desc: null
  value: 169
strides13:
  desc: null
  value: 213
pool_kernel13:
  desc: null
  value: 7
stride_kernel13:
  desc: null
  value: 10
kernel_size_14:
  desc: null
  value: 21
padding_14:
  desc: null
  value: 15
bias_14:
  desc: null
  value: false
channels_14:
  desc: null
  value: 252
strides14:
  desc: null
  value: 179
pool_kernel14:
  desc: null
  value: 10
stride_kernel14:
  desc: null
  value: 2
kernel_size_15:
  desc: null
  value: 3
padding_15:
  desc: null
  value: 12
bias_15:
  desc: null
  value: true
channels_15:
  desc: null
  value: 178
strides15:
  desc: null
  value: 231
pool_kernel15:
  desc: null
  value: 2
stride_kernel15:
  desc: null
  value: 5
kernel_size_16:
  desc: null
  value: 12
padding_16:
  desc: null
  value: 19
bias_16:
  desc: null
  value: true
channels_16:
  desc: null
  value: 217
strides16:
  desc: null
  value: 120
pool_kernel16:
  desc: null
  value: 7
stride_kernel16:
  desc: null
  value: 1
kernel_size_17:
  desc: null
  value: 16
padding_17:
  desc: null
  value: 17
bias_17:
  desc: null
  value: false
channels_17:
  desc: null
  value: 186
strides17:
  desc: null
  value: 162
pool_kernel17:
  desc: null
  value: 4
stride_kernel17:
  desc: null
  value: 2
kernel_size_18:
  desc: null
  value: 3
padding_18:
  desc: null
  value: 3
bias_18:
  desc: null
  value: false
channels_18:
  desc: null
  value: 169
strides18:
  desc: null
  value: 52
pool_kernel18:
  desc: null
  value: 7
stride_kernel18:
  desc: null
  value: 3
kernel_size_19:
  desc: null
  value: 18
padding_19:
  desc: null
  value: 14
bias_19:
  desc: null
  value: false
channels_19:
  desc: null
  value: 227
strides19:
  desc: null
  value: 154
pool_kernel19:
  desc: null
  value: 9
stride_kernel19:
  desc: null
  value: 4
kernel_size_20:
  desc: null
  value: 31
padding_20:
  desc: null
  value: 20
bias_20:
  desc: null
  value: false
channels_20:
  desc: null
  value: 20
strides20:
  desc: null
  value: 278
pool_kernel20:
  desc: null
  value: 10
stride_kernel20:
  desc: null
  value: 5
kernel_size_21:
  desc: null
  value: 3
padding_21:
  desc: null
  value: 16
bias_21:
  desc: null
  value: true
channels_21:
  desc: null
  value: 113
strides21:
  desc: null
  value: 224
pool_kernel21:
  desc: null
  value: 1
stride_kernel21:
  desc: null
  value: 4
kernel_size_22:
  desc: null
  value: 35
padding_22:
  desc: null
  value: 12
bias_22:
  desc: null
  value: true
channels_22:
  desc: null
  value: 76
strides22:
  desc: null
  value: 133
pool_kernel22:
  desc: null
  value: 2
stride_kernel22:
  desc: null
  value: 5
kernel_size_23:
  desc: null
  value: 44
padding_23:
  desc: null
  value: 16
bias_23:
  desc: null
  value: false
channels_23:
  desc: null
  value: 229
strides23:
  desc: null
  value: 161
pool_kernel23:
  desc: null
  value: 6
stride_kernel23:
  desc: null
  value: 7
kernel_size_24:
  desc: null
  value: 16
padding_24:
  desc: null
  value: 4
bias_24:
  desc: null
  value: true
channels_24:
  desc: null
  value: 234
strides24:
  desc: null
  value: 42
pool_kernel24:
  desc: null
  value: 4
stride_kernel24:
  desc: null
  value: 1
kernel_size_25:
  desc: null
  value: 27
padding_25:
  desc: null
  value: 13
bias_25:
  desc: null
  value: false
channels_25:
  desc: null
  value: 17
strides25:
  desc: null
  value: 74
pool_kernel25:
  desc: null
  value: 1
stride_kernel25:
  desc: null
  value: 9
kernel_size_26:
  desc: null
  value: 7
padding_26:
  desc: null
  value: 19
bias_26:
  desc: null
  value: true
channels_26:
  desc: null
  value: 26
strides26:
  desc: null
  value: 75
pool_kernel26:
  desc: null
  value: 4
stride_kernel26:
  desc: null
  value: 7
kernel_size_27:
  desc: null
  value: 48
padding_27:
  desc: null
  value: 14
bias_27:
  desc: null
  value: false
channels_27:
  desc: null
  value: 140
strides27:
  desc: null
  value: 200
pool_kernel27:
  desc: null
  value: 1
stride_kernel27:
  desc: null
  value: 3
kernel_size_28:
  desc: null
  value: 25
padding_28:
  desc: null
  value: 2
bias_28:
  desc: null
  value: false
channels_28:
  desc: null
  value: 169
strides28:
  desc: null
  value: 200
pool_kernel28:
  desc: null
  value: 1
stride_kernel28:
  desc: null
  value: 5
kernel_size_29:
  desc: null
  value: 35
padding_29:
  desc: null
  value: 12
bias_29:
  desc: null
  value: false
channels_29:
  desc: null
  value: 163
strides29:
  desc: null
  value: 50
pool_kernel29:
  desc: null
  value: 3
stride_kernel29:
  desc: null
  value: 10
