wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711299642.0
    t:
      1:
      - 1
      - 35
      - 41
      - 55
      2:
      - 1
      - 35
      - 41
      - 55
      3:
      - 2
      - 23
      4: 3.11.7
      5: 0.16.4
      8:
      - 3
      - 5
      13: windows-amd64
n_layers:
  desc: null
  value: 5
lr:
  desc: null
  value: 0.03289385723425191
optimizer:
  desc: null
  value: SGD
features_lineales:
  desc: null
  value: 474
kernel_size_0:
  desc: null
  value: 2
padding_0:
  desc: null
  value: 2
bias_0:
  desc: null
  value: false
channels_0:
  desc: null
  value: 2
strides0:
  desc: null
  value: 1
pool_kernel0:
  desc: null
  value: 2
stride_kernel0:
  desc: null
  value: 1
kernel_size_1:
  desc: null
  value: 4
padding_1:
  desc: null
  value: 1
bias_1:
  desc: null
  value: false
channels_1:
  desc: null
  value: 1
strides1:
  desc: null
  value: 2
pool_kernel1:
  desc: null
  value: 2
stride_kernel1:
  desc: null
  value: 1
kernel_size_2:
  desc: null
  value: 5
padding_2:
  desc: null
  value: 2
bias_2:
  desc: null
  value: false
channels_2:
  desc: null
  value: 1
strides2:
  desc: null
  value: 1
pool_kernel2:
  desc: null
  value: 1
stride_kernel2:
  desc: null
  value: 1
kernel_size_3:
  desc: null
  value: 3
padding_3:
  desc: null
  value: 2
bias_3:
  desc: null
  value: false
channels_3:
  desc: null
  value: 1
strides3:
  desc: null
  value: 1
pool_kernel3:
  desc: null
  value: 1
stride_kernel3:
  desc: null
  value: 2
kernel_size_4:
  desc: null
  value: 4
padding_4:
  desc: null
  value: 1
bias_4:
  desc: null
  value: true
channels_4:
  desc: null
  value: 2
strides4:
  desc: null
  value: 1
pool_kernel4:
  desc: null
  value: 1
stride_kernel4:
  desc: null
  value: 1
